# Generated by Django 5.2 on 2025-04-15 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
            ],
            options={
                'db_table_comment': 'Table containing "forms" which consist of a series of "questions" a respondent was asked.',
                'ordering': ['created_date', 'form_name'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Respondent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_no', models.CharField(max_length=255, unique=True)),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('NB', 'Non-Binary')], default='NB', max_length=2)),
                ('ward', models.CharField(max_length=255)),
                ('village', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('citizenship', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('contact_no', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table_comment': 'Basic information about respondents/clients.',
                'ordering': ['lname', 'fname'],
            },
        ),
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ['question', 'option_text']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['question_text']},
        ),
        migrations.AlterModelOptions(
            name='response',
            options={'ordering': ['response_date', 'form', 'respondent']},
        ),
        migrations.AlterModelTableComment(
            name='option',
            table_comment='Table with options associated with a particular question.',
        ),
        migrations.AlterModelTableComment(
            name='question',
            table_comment='Table containing questions that a respondent may be asked. This may include questions about services provided to a client.',
        ),
        migrations.AlterModelTableComment(
            name='response',
            table_comment='Table containing responses, or an instance of a respondent completing a survey.',
        ),
        migrations.RemoveField(
            model_name='response',
            name='option',
        ),
        migrations.AddField(
            model_name='option',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('Text', 'Text'), ('Yes/No', 'Yes/No'), ('Number', 'Number'), ('Single Selection', 'Single Selection'), ('Multiple Selections', 'Multiple Selections')], default='Text', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='response',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='option_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='response',
            name='response_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_answer', models.TextField(blank=True)),
                ('option', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='forms.option')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.question')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.response')),
            ],
            options={
                'db_table_comment': 'Table containing the actual answers to questions a respondent gave.',
                'ordering': ['response', 'question', 'option'],
            },
        ),
        migrations.AddField(
            model_name='response',
            name='form',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='forms.form'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='form',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms.organization'),
        ),
        migrations.AddField(
            model_name='response',
            name='respondent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='forms.respondent'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='FormQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.form')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.question')),
            ],
            options={
                'db_table_comment': 'Table containing a list of questions asked in a particular form.',
                'ordering': ['form', 'question'],
                'unique_together': {('form', 'question')},
            },
        ),
    ]
