# Generated by Django 5.2 on 2025-04-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_form_organization_respondent_alter_option_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='form',
            options={'ordering': ['-created_date', 'form_name']},
        ),
        migrations.AlterModelOptions(
            name='response',
            options={'ordering': ['-response_date', 'form', 'respondent']},
        ),
        migrations.AddField(
            model_name='formquestion',
            name='index',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='respondent',
            name='citizenship',
            field=models.CharField(max_length=255, verbose_name='Citizenship/Nationality'),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='contact_no',
            field=models.CharField(max_length=255, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='district',
            field=models.CharField(max_length=255, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='fname',
            field=models.CharField(max_length=255, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='id_no',
            field=models.CharField(max_length=255, unique=True, verbose_name='ID/Passport Number'),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='lname',
            field=models.CharField(max_length=255, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('NB', 'Non-Binary')], default='NB', max_length=2, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='village',
            field=models.CharField(max_length=255, verbose_name='Village'),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='ward',
            field=models.CharField(max_length=255, verbose_name='Ward'),
        ),
    ]
