# Generated by Django 4.2.20 on 2025-05-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0016_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='access_level',
            field=models.CharField(choices=[('data-collector', 'Data Collector'), ('supervisor', 'Supervisor'), ('manager', 'Manager'), ('admin', 'Administrator')], default='data-collector', max_length=100),
        ),
    ]
