# Generated by Django 4.2.20 on 2025-05-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0019_alter_formlogic_conditional_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='formlogicrule',
            name='value_comparison',
            field=models.CharField(choices=[('MATCHES', 'AND'), ('CONTAINS', 'OR'), ('DOES NOT CONTAIN', 'DOES NOT CONTAIN'), ('EQAUL TO', 'EQUAL TO'), ('GREATER THAN', 'GREATER THAN'), ('LESS THAN', 'GREATER THAN')], default=None, blank=True, null=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='formlogic',
            name='conditional_operator',
            field=models.CharField(blank=True, choices=[('AND', 'AND'), ('OR', 'OR')], default=None, max_length=255, null=True),
        ),
    ]
