# Generated by Django 4.2.20 on 2025-05-06 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0021_alter_formlogicrule_value_comparison'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formlogicrule',
            name='value_comparison',
        ),
    ]
