# Generated by Django 4.2.20 on 2025-05-07 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0025_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='match_option',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.option'),
        ),
    ]
