# Generated by Django 4.2.20 on 2025-05-08 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0026_target_match_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='parent_organization',
        ),
        migrations.RemoveField(
            model_name='target',
            name='match_option',
        ),
        migrations.RemoveField(
            model_name='target',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='target',
            name='question',
        ),
    ]
