# Generated by Django 4.2.20 on 2025-05-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0029_alter_form_organization_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='special',
            field=models.CharField(blank=True, choices=[('MATCHES', 'MATCHES'), ('CONTAINS', 'CONTAINS')], default=None, max_length=255, null=True),
        ),
    ]
