# Generated by Django 4.2.20 on 2025-05-20 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0032_alter_option_special'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formlogic',
            name='limit_options',
        ),
        migrations.AddField(
            model_name='formlogicrule',
            name='limit_options',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
