# Generated by Django 4.2.20 on 2025-05-08 08:34

from django.db import migrations, models
import django.db.models.deletion
import organizations.models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='organization',
            field=models.ForeignKey(default=organizations.models.Organization.get_default_pk, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
    ]
