# Generated by Django 4.2.20 on 2025-06-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_target_as_percentage_target_percentage_of_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='ed_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Exeuctive Director Email Address'),
        ),
        migrations.AddField(
            model_name='organization',
            name='ed_no',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Exeuctive Director Phone Number'),
        ),
        migrations.AddField(
            model_name='organization',
            name='executive_director',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of Executive Director'),
        ),
        migrations.AddField(
            model_name='organization',
            name='office_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Office Address'),
        ),
        migrations.AddField(
            model_name='organization',
            name='office_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Office Email Address'),
        ),
        migrations.AddField(
            model_name='organization',
            name='office_no',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Office Phone Number'),
        ),
    ]
