# Generated by Django 4.2.20 on 2025-05-08 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import organizations.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0002_alter_target_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('data-collector', 'Data Collector'), ('supervisor', 'Supervisor'), ('manager', 'Manager'), ('admin', 'Administrator')], default='data-collector', max_length=100)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, default=organizations.models.Organization.get_default_pk, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.organization')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
