# Generated by Django 4.2.20 on 2025-05-09 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0029_alter_form_organization_delete_userprofile'),
        ('organizations', '0002_alter_target_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='as_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='target',
            name='percentage_of_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='percent_of_question', to='forms.question'),
        ),
        migrations.AlterField(
            model_name='target',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_question', to='forms.question'),
        ),
        migrations.AlterField(
            model_name='target',
            name='target_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
