# Generated by Django 5.2 on 2025-04-14 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_option_delete_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_date', models.DateTimeField(verbose_name='date published')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.option')),
            ],
        ),
    ]
