# Generated by Django 4.2.20 on 2025-05-05 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0017_userprofile_access_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormLogic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_match', models.CharField(choices=[('Show', 'Show'), ('Hide', 'Hide')], default=None, max_length=255)),
                ('conditional_operator', models.CharField(blank=True, choices=[('AND', 'AND'), ('OR', 'OR')], default=None, max_length=10, null=True)),
                ('limit_options', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='formquestion',
            name='visible_if_answer',
        ),
        migrations.RemoveField(
            model_name='formquestion',
            name='visible_if_question',
        ),
        migrations.CreateModel(
            name='FormLogicRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_values', models.JSONField()),
                ('negate_value', models.BooleanField(default=False)),
                ('form_logic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.formlogic')),
                ('parent_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.formquestion')),
            ],
        ),
        migrations.AddField(
            model_name='formlogic',
            name='conditional_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.formquestion'),
        ),
        migrations.AddField(
            model_name='formlogic',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.form'),
        ),
    ]
