# Generated by Django 4.2.20 on 2025-05-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0018_formlogic_remove_formquestion_visible_if_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formlogic',
            name='conditional_operator',
            field=models.CharField(blank=True, choices=[('AND', 'AND'), ('OR', 'OR'), ('GREATER THAN', 'GREATER THAN'), ('LESS THAN', 'LESS THAN'), ('CONTAINS', 'CONTAINS')], default=None, max_length=255, null=True),
        ),
    ]
