# Generated by Django 4.2.20 on 2025-05-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0020_formlogicrule_value_comparison_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formlogicrule',
            name='value_comparison',
            field=models.CharField(blank=True, choices=[('MATCHES', 'AND'), ('CONTAINS', 'OR'), ('DOES NOT CONTAIN', 'DOES NOT CONTAIN'), ('EQAUL TO', 'EQUAL TO'), ('GREATER THAN', 'GREATER THAN'), ('LESS THAN', 'GREATER THAN')], default=None, max_length=255, null=True),
        ),
    ]
