# Generated by Django 4.2.20 on 2025-05-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0023_formlogicrule_value_comparison'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formlogicrule',
            name='value_comparison',
            field=models.CharField(blank=True, choices=[('MATCHES', 'MATCHES'), ('CONTAINS', 'CONTAINS'), ('DOES NOT CONTAIN', 'DOES NOT CONTAIN'), ('EQAUL TO', 'EQUAL TO'), ('GREATER THAN', 'GREATER THAN'), ('LESS THAN', 'GREATER THAN')], default=None, max_length=255, null=True),
        ),
    ]
