# Generated by Django 4.2.20 on 2025-05-07 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0024_alter_formlogicrule_value_comparison'),
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_amount', models.IntegerField()),
                ('target_start', models.DateField(verbose_name='Target Period Start')),
                ('target_end', models.DateField(verbose_name='Target Period End')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.organization')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.question')),
            ],
        ),
    ]
