# Generated by Django 4.2.20 on 2025-05-08 08:34

from django.db import migrations, models
import django.db.models.deletion
import organizations.models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_target_organization'),
        ('forms', '0028_alter_form_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='organization',
            field=models.ForeignKey(default=organizations.models.Organization.get_default_pk, on_delete=django.db.models.deletion.PROTECT, to='organizations.organization'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
