# Generated by Django 4.2.20 on 2025-05-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0030_option_special'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='special',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('All', 'All')], default=None, max_length=255, null=True),
        ),
    ]
